baseurl: ""
url: "https://italgel.com.co"
name: "italgel.com.co"
logo: img/logo.avif
social_image: img/contacto-italgel-colombia.jpg
author: Sebastián Rios
telefono: 573192346788
email: info@mec3.co
direccion: "Calle 68 No 68B - 74, Bogotá, Colombia"

markdown: kramdown

permalink: :slug/

keep_files: [/img]

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

plugins:
  - jekyll-redirect-from

collections:
  posts:
    output: true
    permalink: /blog/:slug/
