baseurl: ''
url: 'https://italgel.com.co'
name: 'italgel.com.co'
logo: img/logo.webp
author: Sebastián Rios
telefono: 3166926111
whatsapp_message: "Hola, quiero más información sobre los helados artesanales"

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  ciudades:
    output: true
    permalink: /productos/:path
  posts:
    output: true
    permalink: /blog/:slug
